#!/usr/bin/env python3
"""Embed the T6-extracted sprites into shim/sprites.inc for the emscripten
build (Task 20).

Source: web/assets/resources.json (M1 extraction) -> web/assets/
sprites/bmp_NNN.png, 89 bitmaps, ids 1..0x59, all 4bpp indexed in the
original PE. The PNGs are the PALETTE-CORRECTED RGB extraction of the raw
4bpp DIB pixels (harness/extract_resources.py; Windows RGBQUADs are b,g,r
in the file, so the PNG RGB is the resource's true color per index).

Storage: 32bpp RGBA (this script emits the RGB rows; surface.c adds alpha
0xFF). This is not a shortcut — wine 9.0 (the reference's GDI) converts a
loaded 4bpp resource DIB to a 32bpp DEVICE bitmap: LoadBitmapA + GetObjectA
on a 4bpp RT_BITMAP reports bmBitsPixel=32 (T20 probe, /tmp/t20probe:
q2..q4.bmp 4bpp DIBs, wine 9.0, WINEPREFIX=~/.wine-ski, Xvfb :99; the
4bpp GetDIBits readback fails E_INVALIDARG because the DIB is no longer
4bpp after load). The M2 rebuild's 24bpp windres bitmaps converted the
same way, so both reference runs saw 32bpp here too.

ROP consequences (documented in surface.h / misc.c):
  - SRCCOPY sprite -> 32bpp image strip (ski_core.c:331): the palette-
    expanded RGB IS the result — byte-identical to wine's conversion.
  - NOTSRCCOPY sprite -> 1bpp mask strip (ski_core.c:332): wine's rule for
    4bpp sources is "bit set iff the PALETTE-EXPANDED color != 0xFFFFFF"
    — the same compare as the 32bpp->1bpp rule T17 measured (probe_mono.c
    Q1: [white,red,black,blue] -> bits 0 1 1 1). T20 probed the 4bpp case
    directly with real RT_BITMAP 4bpp DIBs (discriminators below); the
    index is never compared directly:
      Q2 pal [red,white,green,black]  px idx [0,1,2,3] -> bits 1 0 1 1
         (index!=0 rule would give 0 1 1 1)
      Q3 pal [white,white,red,black]  px idx [0,1,2,3] -> bits 0 0 1 1
         (index!=white-idx-0 rule would give 0 1 1 1; index!=0 gives
         1 0 1 1) — both rejected: only palette-expanded RGB != white fits.
      Q4 pal [white,red,green,black]  (the real ski32 shape: background
         white) px idx [0,1,2,3] -> bits 0 1 1 1 (consistent; also the
         M2 0px-parity prediction: original 4bpp mask == rebuild 24bpp
         mask under the "not white" rule).
    So the existing 32bpp->1 ROP (bit = px != SHIM_MONO_ON, SHIM_MONO_ON
    = white) implements the 4bpp rule exactly on these pre-expanded
    pixels — no index is ever lost.

All 89 resources are 4bpp (resources.json bpp distribution checked: 89x4).
A non-4bpp entry fails loudly: the RGB PNGs exist for the 4bpp resources
only. Idempotent; regenerate after touching web/assets/.
"""
import json
import pathlib

import PIL.Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = json.loads((ROOT / "web" / "assets" / "resources.json").read_text())
OUT = ROOT / "shim" / "sprites.inc"

H = []
H.append("/* Generated by harness/embed_sprites.py — DO NOT EDIT.         ")
H.append(" * Sprite pixels for the emscripten shim (Task 20): the 89      ")
H.append(" * T6-extracted 4bpp RT_BITMAPs as palette-expanded RGB rows    ")
H.append(" * (see the script header for the wine 4bpp->32bpp/1bpp         ")
H.append(" * conversion evidence). px = w*h*3 bytes, row-major, top-      ")
H.append(" * down, (R,G,B) per pixel.                                     ")
H.append(" */")
H.append("typedef struct ShimSprite {")
H.append("    int id, w, h;")
H.append("    const unsigned char *px; /* RGB rows, w*h*3 bytes */")
H.append("} ShimSprite;")

entries = []
for bid in sorted(RES["bitmaps"], key=int):
    meta = RES["bitmaps"][bid]
    if meta["bpp"] != 4:
        raise SystemExit(f"sprites: id {bid} is {meta['bpp']}bpp — unsupported")
    im = PIL.Image.open(ROOT / meta["file"]).convert("RGB")
    w, h = im.size
    if (w, h) != (meta["w"], meta["h"]):
        raise SystemExit(f"sprites: id {bid} PNG size {w}x{h} != {meta['w']}x{meta['h']}")
    data = im.tobytes("raw", "RGB")
    name = f"spr_px_{int(bid):03d}"
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ("," if i + 16 < len(data) else ""))
    H.append(f"static const unsigned char {name}[{len(data)}] = {{")
    H.extend(lines)
    H.append("};")
    entries.append(f"    {{{int(bid)}, {w}, {h}, {name}}}")

H.append(f"static const ShimSprite g_sprites[{len(entries)}] = {{")
H.append(",\n".join(entries))
H.append("};")
OUT.write_text("\n".join(H) + "\n")
print(f"OK: {OUT} ({len(entries)} sprites)")
