#!/usr/bin/env python3
"""Scenario JSON -> ski_in.bin (one little-endian u16 per tick) + ski_keys.h.

Usage: gen_input.py SCENARIO_JSON OUT_BIN [--emit-header src/ski_keys.h]

Input contract (M1: the binary has NO key-state polling and NO WM_KEYUP —
input is edge-triggered WM_KEYDOWN only, so each set bit at tick t means
exactly ONE WM_KEYDOWN(vk) is delivered to the main window at the start of
tick t; no repeats, no up events). "down": false events are no-ops and
exist for JSON round-tripping only.

Bit layout (fixed; one u16 per tick):
  bit 0  left      (VK_LEFT / Numpad4)
  bit 1  right     (VK_RIGHT / Numpad6)
  bit 2  up        (VK_UP / Numpad8)
  bit 3  down      (VK_DOWN / Numpad2)
  bit 4  crouch    (VK_NUMPAD0 / Insert)
  bit 5  facing1   (VK_NUMPAD1)
  bit 6  facing3   (VK_NUMPAD3)
  bit 7  facing7   (VK_NUMPAD7)
  bit 8  facing9   (VK_NUMPAD9)
  bit 9  restart   (VK_F2)
  bit 10 pause     (VK_F3)
  bit 11 advance   (VK_RETURN)

The VK symbols come from harness/seed.json ("keys"), which is the
2026-08-25/26 verified keymap (see decompile/NOTES.md M1 answers).
"""
import json
import pathlib
import sys

KEY_BITS = [
    "left", "right", "up", "down", "crouch",
    "facing1", "facing3", "facing7", "facing9",
    "restart", "pause", "advance",
]
# seed.json keys entries that exist for every key above
SEED_KEYS = {
    "left": "left", "right": "right", "up": "up", "down": "down",
    "crouch": "crouch",
    "facing1": "facing1", "facing3": "facing3",
    "facing7": "facing7", "facing9": "facing9",
    "restart": "restart", "pause": "pause", "advance": "advance",
}


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    here = pathlib.Path(__file__).resolve().parent
    sc = json.loads(pathlib.Path(sys.argv[1]).read_text())
    seed = json.loads((here / "seed.json").read_text())
    keys = seed["keys"]

    out = [0] * int(sc["ticks"])
    per_key = {k: 0 for k in KEY_BITS}
    for ev in sc["events"]:
        k = ev["key"]
        if k not in per_key:
            print(f"error: unknown key {k!r} (layout: {KEY_BITS})", file=sys.stderr)
            return 2
        if not ev.get("down", True):
            continue  # no WM_KEYUP path in the binary: no-op
        t = int(ev["t"])
        if not (0 <= t < len(out)):
            print(f"error: event t={t} outside 0..{len(out)-1}", file=sys.stderr)
            return 2
        out[t] |= 1 << KEY_BITS.index(k)
        per_key[k] += 1

    pathlib.Path(sys.argv[2]).write_bytes(
        b"".join(v.to_bytes(2, "little") for v in out)
    )
    print(f"wrote {sys.argv[2]}: {len(out)} ticks (2 bytes/tick)")
    active = {k: n for k, n in per_key.items() if n}
    print(f"events: {active or 'none'}")

    if "--emit-header" in sys.argv:
        hdr = pathlib.Path(sys.argv[sys.argv.index("--emit-header") + 1])
        lines = [
            "/* generated by harness/gen_input.py — do not edit */",
            "#ifndef SKI_KEYS_H",
            "#define SKI_KEYS_H",
            "/* One WM_KEYDOWN per set bit at tick start; see gen_input.py. */",
        ]
        for i, k in enumerate(KEY_BITS):
            sym = keys[SEED_KEYS[k]]
            lines.append(f"#define SKI_BIT_{k.upper():10s} {i}")
            lines.append(f"#define SKI_VK_{k.upper():10s} {sym}")
        lines.append(f"#define SKI_NUM_KEYS      {len(KEY_BITS)}")
        lines.append("#endif /* SKI_KEYS_H */")
        hdr.write_text("\n".join(lines) + "\n")
        print(f"wrote {hdr}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
