#!/usr/bin/env python3
import json, pathlib
cfg = json.loads(pathlib.Path("harness/seed.json").read_text())
pathlib.Path("src/seed_values.h").write_text(
    "/* generated by harness/gen_seed_header.py — do not edit */\n"
    f"#define SKI_SEED_CONSTANT {cfg['seed_constant']}\n"
    f"/* timing: {cfg['timing']['model']}, settimer_ms={cfg['timing']['settimer_ms']} */\n")
print("wrote src/seed_values.h")
