#!/usr/bin/env python3
"""Assemble the single-file portable build: web/ski32.html.

Embeds the emscripten loader (web/ski.js), the game glue (web/boot.js) and
the wasm binary (web/ski.wasm) directly into one HTML file, so the whole
game runs from a single portable file with no network requests. The font is
already compiled into the wasm (shim/font.inc), so the wasm is the only
runtime asset to embed.

How the embedded wasm is loaded: boot.js's skiWasmOpts() sees
window.__SKI_WASM_B64__ (set here) and hands the decoded bytes to
Module.instantiateWasm (ski.js:623), which makes emscripten skip the
ski.wasm fetch entirely. In the multi-file page (index.html) that var is
absent, so the same boot.js fetches ski.wasm as usual.

The input files are the SHIPPING build (build-web, -DSKI_HARNESS=OFF), which
is what web/ holds, plus the favicon (web/assets/favicon.gif). Rebuild first
(see README), then run:
    python3 harness/make_single_file.py
Output is web/ski32.html — the single-file "final" product (committed, so it
can be opened directly or shared without a build; regenerate after a rebuild).
"""
import base64
import hashlib
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parent.parent
web = root / "web"


def fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def read(name: str) -> str:
    p = web / name
    if not p.is_file():
        fail(f"{p} not found — build the web target first (see README)")
    return p.read_text(encoding="utf-8")


def read_bytes(name: str) -> bytes:
    p = web / name
    if not p.is_file():
        fail(f"{p} not found — build the web target first (see README)")
    return p.read_bytes()


index_html = read("index.html")
ski_js = read("ski.js")
boot_js = read("boot.js")
wasm = read_bytes("ski.wasm")
favicon = read_bytes("assets/favicon.gif")
favicon_b64 = base64.b64encode(favicon).decode("ascii")

# Reuse index.html's <style> + <canvas> verbatim so the single file matches
# the multi-file page exactly (canvas size, CSS auto-scale, pixelated render).
m_style = re.search(r"<style>.*?</style>", index_html, re.DOTALL)
m_canvas = re.search(r'<canvas[^>]*></canvas>', index_html, re.DOTALL)
if not m_style or not m_canvas:
    fail("could not extract <style> / <canvas> from index.html")
style, canvas = m_style.group(0), m_canvas.group(0)

# base64 -> a JS expression. Chunk into 1000-char string literals joined by
# '+' so no single line is absurdly long (base64 has no quote chars, so this
# is safe to inline verbatim).
b64 = base64.b64encode(wasm).decode("ascii")
chunks = [b64[i : i + 1000] for i in range(0, len(b64), 1000)]
wasm_expr = " +\n".join(f'  "{c}"' for c in chunks)

# Guard against an accidental </script> in any inlined script (there is none
# today — verified — but fail loudly rather than emit a broken file).
for name, body in (("ski.js", ski_js), ("boot.js", boot_js)):
    if "</script" in body.lower():
        fail(f"{name} contains a </script> sequence — would break inlining")

out = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>SkiFree 1.04</title>
<link rel="icon" type="image/gif" href="data:image/gif;base64,{favicon_b64}">
{style}
</head>
<body>
<!-- SkiFree 1.04 32-bit, decompiled + ported to WebAssembly. Single-file
     build: the emscripten loader, the game glue and the wasm binary are all
     embedded below — no external requests. Generated by
     harness/make_single_file.py from the shipping build (web/ski.js,
     web/ski.wasm, web/boot.js). The font is compiled into the wasm. -->
{canvas}
<script>
/* embedded wasm binary (base64) — consumed by boot.js's skiWasmOpts() */
window.__SKI_WASM_B64__ =
{wasm_expr}
;
</script>
<script>
/* ==== ski.js — emscripten loader (inlined) ==== */
{ski_js}
</script>
<script>
/* ==== boot.js — game boot / input / modal (inlined) ==== */
{boot_js}
</script>
</body>
</html>
"""

out_path = web / "ski32.html"
out_path.write_text(out, encoding="utf-8")
wasm_sha = hashlib.sha256(wasm).hexdigest()[:16]
html_sha = hashlib.sha256(out.encode("utf-8")).hexdigest()[:16]
print(
    f"wrote {out_path} ({out_path.stat().st_size:,} bytes; "
    f"wasm {len(wasm):,} B sha256:{wasm_sha}; html sha256:{html_sha})"
)
