/* generated by harness/gen_input.py — do not edit */
#ifndef SKI_KEYS_H
#define SKI_KEYS_H
/* One WM_KEYDOWN per set bit at tick start; see gen_input.py. */
#define SKI_BIT_LEFT       0
#define SKI_VK_LEFT       VK_LEFT
#define SKI_BIT_RIGHT      1
#define SKI_VK_RIGHT      VK_RIGHT
#define SKI_BIT_UP         2
#define SKI_VK_UP         VK_UP
#define SKI_BIT_DOWN       3
#define SKI_VK_DOWN       VK_DOWN
#define SKI_BIT_CROUCH     4
#define SKI_VK_CROUCH     VK_NUMPAD0
#define SKI_BIT_FACING1    5
#define SKI_VK_FACING1    VK_NUMPAD1
#define SKI_BIT_FACING3    6
#define SKI_VK_FACING3    VK_NUMPAD3
#define SKI_BIT_FACING7    7
#define SKI_VK_FACING7    VK_NUMPAD7
#define SKI_BIT_FACING9    8
#define SKI_VK_FACING9    VK_NUMPAD9
#define SKI_BIT_RESTART    9
#define SKI_VK_RESTART    VK_F2
#define SKI_BIT_PAUSE      10
#define SKI_VK_PAUSE      VK_F3
#define SKI_BIT_ADVANCE    11
#define SKI_VK_ADVANCE    VK_RETURN
#define SKI_NUM_KEYS      12
#endif /* SKI_KEYS_H */
